version: "3.9"

services:
  api:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  frontend:
    build: ./frontend
    container_name: personal-cfo-frontend
    depends_on:
      - api
    ports:
      - "5173:80"          # browser hits localhost:5173
    restart: unless-stopped
    
volumes:
  db_data:
